import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav style={{ margin: "2rem 0" }}>
          <a href="/static" style={{ marginRight: "1rem" }}>
            Static
          </a>
          <a href="/dynamic" style={{ marginRight: "1rem" }}>
            Dynamic
          </a>
          <a href="/hybrid">Hybrid</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
